{"name": "test_change_data_auth_user", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range", "trace": "self = <test_change_data_user.TestDataChange object at 0x000001D50A706F60>\n\n    @allure.step('Изменение данных пользователя с авторизацией')\n    def test_change_data_auth_user(self):\n>       token = get_token()\n\ntests\\test_change_data_user.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nhelpers.py:52: in get_token\n    login = login_user()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    @allure.step('Логин пользователя')\n    def login_user():\n        login_pass = registration_user()\n        payload = {\n>           'email': login_pass[0],\n            'password': login_pass[1]\n        }\nE       IndexError: list index out of range\n\nhelpers.py:43: IndexError"}, "steps": [{"name": "Изменение данных пользователя с авторизацией", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\tests\\test_change_data_user.py\", line 11, in test_change_data_auth_user\n    token = get_token()\n            ^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\helpers.py\", line 52, in get_token\n    login = login_user()\n            ^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\helpers.py\", line 43, in login_user\n    'email': login_pass[0],\n             ~~~~~~~~~~^^^\n"}, "steps": [{"name": "Получение токена", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\helpers.py\", line 52, in get_token\n    login = login_user()\n            ^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\helpers.py\", line 43, in login_user\n    'email': login_pass[0],\n             ~~~~~~~~~~^^^\n"}, "steps": [{"name": "Логин пользователя", "status": "broken", "statusDetails": {"message": "IndexError: list index out of range\n", "trace": "  File \"C:\\Users\\Галина\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Галина\\Documents\\Yandex_praktikum\\Diplom\\Diplom_2\\Diplom_2\\helpers.py\", line 43, in login_user\n    'email': login_pass[0],\n             ~~~~~~~~~~^^^\n"}, "steps": [{"name": "Регистрация пользователя", "status": "passed", "start": 1724619056775, "stop": 1724619057168}], "start": 1724619056775, "stop": 1724619057168}], "start": 1724619056775, "stop": 1724619057258}], "start": 1724619056775, "stop": 1724619057258}], "start": 1724619056775, "stop": 1724619057259, "uuid": "58eba6f9-7a31-4572-9de3-f327ac726977", "historyId": "1d081a4f17b061e20d135824811da3e0", "testCaseId": "1d081a4f17b061e20d135824811da3e0", "fullName": "tests.test_change_data_user.TestDataChange#test_change_data_auth_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_data_user"}, {"name": "subSuite", "value": "TestDataChange"}, {"name": "host", "value": "LAPTOP-4UNN3S2K"}, {"name": "thread", "value": "2996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_data_user"}]}